# ============================================================================
# Config file for Ribofinder
#
# ==================[ Sections for the users ]================================
#
# One of input_directory, input_pattern and input_samples must be provided
# If input_directory provided, use it otherwise if input_pattern provided,
# use it, otherwise use input_samples.
# ============================================================================

input_directory:
input_readtag: _R[12]_
input_pattern: '*fastq.gz'
# =========================================== Sections for the users

#############################################################################
# Genome section:
#
# :Parameters:
#
# - aligner: bowtie2 or bwa
# - rRNA_file: path to an existing fasta file for ribosomal RNA
# - rRNA_feature: if rRNA_file is not provided, ribosomal RNA will be extracted
#     from GFF using this feature name. It must be found.
#
#   Only one annotation file must be provided. If so, we extract the feature
#   rRNA from the annotation, identify start/end and create fasta file on the
#   fly. You may simply provide an input fasta file with rRNA if you have one.
general:
    aligner: bowtie2
    rRNA_file: ''
    rRNA_feature: rRNA
    genbank_file: ''
    gff_file:
    reference_file:

apptainers:
    sequana_tools: "https://zenodo.org/record/18257162/files/sequana_tools_26.1.14.img"
    pigz: "https://zenodo.org/record/7346805/files/pigz_2.4.0.img"
    graphviz: "https://zenodo.org/record/7928262/files/graphviz_7.0.5.img"
    multiqc: "https://zenodo.org/record/10205070/files/multiqc_1.16.0.img"

#############################################################################
# bowtie2_mapping_rna used to align reads against ribosomal RNA
#
# :Parameters:
#
# - options: any options recognised by bowtie2
# - threads: number of threads to be used
#
bowtie2_mapping_rna:
    options: ''
    threads: 4


#############################################################################
# bwa_mapping_rna used to align reads against ribosomal RNA
#
# :Parameters:
#
# - index_algorithm: 'is' (default, small genomes) or 'bwtsw' (large genomes)
# - options: any options recognised by bwa mem
# - threads: number of threads to be used
# - tmp_directory: scratch directory for sambamba sort
#
bwa_mapping_rna:
    index_algorithm: is
    options: ''
    threads: 4
    tmp_directory: ./tmp


#############################################################################
#   MultiQC aggregates results from bioinformatics analyses across many
#   samples into a single report.
#
# :Parameters:
#
# - options: any options recognised by multiqc
# - modules: space-separated multiqc modules to enable
#       ('bowtie2' for bowtie2 aligner, 'samtools' for bwa aligner)
# - config_file: multiqc config file
multiqc:
    options: -f
    input_directory: .
    modules: bowtie2
    config_file: multiqc_config.yaml

