# Schema validator for the ribofinder pipeline
# author: Thomas Cokelaer

type: map
mapping:
    "input_directory":
        type: str
        required: True
    "input_readtag":
        type: str
        required: True
    "input_pattern":
        type: str
        required: True
    "exclude_pattern":
        type: str
        required: False
    "apptainers":
        type: any

    "general":
        type: map
        mapping:
            "aligner":
                type: str
                required: True
                enum: ["bowtie2", "bwa"]
            "rRNA_feature":
                type: str
            "rRNA_file":
                type: str
            "genbank_file":
                type: str
            "reference_file":
                type: str
            "gff_file":
                type: str

    'bowtie2_mapping_rna':
        type: map
        mapping:
            "options":
                type: str
            "threads":
                type: int
                required: True
                range: { min: 1}

    'bwa_mapping_rna':
        type: map
        mapping:
            "index_algorithm":
                type: str
                enum: ["is", "bwtsw", "rb2"]
            "options":
                type: str
            "threads":
                type: int
                required: True
                range: { min: 1}
            "tmp_directory":
                type: str

    "multiqc":
        type: map
        mapping:
            "do":
              type: bool
            "options":
                type: str
            "config_file":
                type: str
            "input_directory":
                type: str
            "output_directory":
                type: str
            "modules":
                type: str
